cuagain:
  port: 8080  # CUAgain 应用程序监听端口
  password: 114514  # 角色资源管理密码
  assets-proxy: false  # 启用角色资源代理
  assets-cache: false  # 启用本地资源缓存
  login-auth: false  # 是否在使用前需要登录认证
  login-password: "Suiseimywife"  # 登录认证密码
  login-timeout: 2880  # 每个IP地址的认证超时时间（分钟）
  get-ip-method: 0  # IP检测方法（0：使用客户端IP或自定义请求头）
  enable-global-holostar-movement: true  # 允许Hololive成员使用Holostar成员的动作
  remove-angle-limit: true  # 移除由角色裙子底部导致的视角限制
  rsa-public-key-path: "rsa/rsa_public_key.pem"  # RSA公钥文件路径
  rsa-private-key-path: "rsa/rsa_private_key.pem"  # RSA私钥文件路径

hololy:
  version-bypass: "2.4.8"  # 绕过Hololy的版本号限制（注意：官方服务停止后无效）