name: Go Cross-Platform Build

# Trigger the workflow on push to main branch and pull requests to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Use a matrix strategy to build on multiple operating systems
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: ['1.23']
    
    # Run the job on each specified operating system
    runs-on: ${{ matrix.os }}
    
    steps:
    # Step 1: Checkout the repository code
    - uses: actions/checkout@v4
    
    # Step 2: Set up the specified Go version
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    # Step 3: Build the project for the current OS
    - name: Build
      env:
        GIN_MODE: release
      run: go build -v ./...
    
    # Step 4: Run tests
    - name: Test
      run: go test -v ./...
    
    # Step 5: Create platform-specific binary artifacts
    - name: Create Binaries
      run: |
        # For Linux and macOS
        if [ "${{ matrix.os }}" != "windows-latest" ]; then
          go build -o myapp-${{ matrix.os }}-${{ matrix.go-version }} ./...
        fi
        
        # For Windows (use .exe extension)
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          go build -o myapp-${{ matrix.os }}-${{ matrix.go-version }}.exe ./...
        fi
    
    # Step 6: Upload artifacts for each build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp-${{ matrix.os }}-${{ matrix.go-version }}
        path: myapp-*
        retention-days: 5
