# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CUAgain

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.0'

    - name: Create build directory
      run: mkdir -p build

    - name: Build
      env:
        GIN_MODE: release
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          mkdir -p build/linux
          GOOS=linux GOARCH=amd64 go build -v -o build/linux/CUAgain ./...
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          mkdir -p build/windows
          GOOS=windows GOARCH=amd64 go build -v -o build/windows/CUAgain.exe ./...
        fi

    - name: Test
      run: go test -v ./...

    - name: Upload files to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: build/
